// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/files_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	entities "expire-share/internal/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileRepo is a mock of FileRepo interface.
type MockFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepoMockRecorder
}

// MockFileRepoMockRecorder is the mock recorder for MockFileRepo.
type MockFileRepoMockRecorder struct {
	mock *MockFileRepo
}

// NewMockFileRepo creates a new mock instance.
func NewMockFileRepo(ctrl *gomock.Controller) *MockFileRepo {
	mock := &MockFileRepo{ctrl: ctrl}
	mock.recorder = &MockFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepo) EXPECT() *MockFileRepoMockRecorder {
	return m.recorder
}

// AddFile mocks base method.
func (m *MockFileRepo) AddFile(ctx context.Context, command commands.AddFile) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFile", ctx, command)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFile indicates an expected call of AddFile.
func (mr *MockFileRepoMockRecorder) AddFile(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFile", reflect.TypeOf((*MockFileRepo)(nil).AddFile), ctx, command)
}

// CountByUserID mocks base method.
func (m *MockFileRepo) CountByUserID(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockFileRepoMockRecorder) CountByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockFileRepo)(nil).CountByUserID), ctx, userID)
}

// DecrementDownloadsByAlias mocks base method.
func (m *MockFileRepo) DecrementDownloadsByAlias(ctx context.Context, alias string) (int16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementDownloadsByAlias", ctx, alias)
	ret0, _ := ret[0].(int16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementDownloadsByAlias indicates an expected call of DecrementDownloadsByAlias.
func (mr *MockFileRepoMockRecorder) DecrementDownloadsByAlias(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementDownloadsByAlias", reflect.TypeOf((*MockFileRepo)(nil).DecrementDownloadsByAlias), ctx, alias)
}

// DeleteExpiredFiles mocks base method.
func (m *MockFileRepo) DeleteExpiredFiles(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredFiles", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredFiles indicates an expected call of DeleteExpiredFiles.
func (mr *MockFileRepoMockRecorder) DeleteExpiredFiles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredFiles", reflect.TypeOf((*MockFileRepo)(nil).DeleteExpiredFiles), ctx)
}

// DeleteFile mocks base method.
func (m *MockFileRepo) DeleteFile(ctx context.Context, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileRepoMockRecorder) DeleteFile(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileRepo)(nil).DeleteFile), ctx, alias)
}

// GetFileByAlias mocks base method.
func (m *MockFileRepo) GetFileByAlias(ctx context.Context, alias string) (entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByAlias", ctx, alias)
	ret0, _ := ret[0].(entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByAlias indicates an expected call of GetFileByAlias.
func (mr *MockFileRepoMockRecorder) GetFileByAlias(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByAlias", reflect.TypeOf((*MockFileRepo)(nil).GetFileByAlias), ctx, alias)
}

// GetFilesByUserID mocks base method.
func (m *MockFileRepo) GetFilesByUserID(ctx context.Context, userID int64) ([]*entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesByUserID indicates an expected call of GetFilesByUserID.
func (mr *MockFileRepoMockRecorder) GetFilesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesByUserID", reflect.TypeOf((*MockFileRepo)(nil).GetFilesByUserID), ctx, userID)
}
