environment: "local" # prod, local, dev
connection_string: "root:makas1506@tcp(127.0.0.1:3306)/ExpireShare?charset=utf8&parseTime=True"
storage:
  type: "local"
  path: "./config/"
  max_file_size: "500mb"
http_server:
  address: "localhost:6010"
  timeout: 4s
  idle_timeout: 60s
service:
  default_ttl: 1h
  default_max_downloads: 1
  alias_length: 6
  file_worker_delay: 5m
  max_file_uploads_per_ip: 5